name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: OpenGL Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev libxcursor-dev

      - name: CMake Generate
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -D WINX_BUILD_EXAMPLE=OFF

      - name: CMake Build
        run: cmake --build ${{ github.workspace }}/build --target winx

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: CMake Generate
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -D WINX_BUILD_EXAMPLE=OFF

      - name: CMake Build
        run: cmake --build ${{ github.workspace }}/build --target winx
